### ISSUE TITLE
Observed Crash

### ISSUE THREAD

**Issue by nginxsantos** [vipshop/hiredis-vip#56]
(gdb) bt
#0  SLL_Pop (list=<optimized out>) at src/linked_list.h:59
#1  Pop (this=<optimized out>) at src/thread_cache.h:208
#2  Allocate (cl=<optimized out>, size=<optimized out>, this=<optimized out>)
    at src/thread_cache.h:364
#3  do_malloc_small (size=<optimized out>, heap=<optimized out>)
    at src/tcmalloc.cc:1182
#4  do_malloc (size=<optimized out>) at src/tcmalloc.cc:1191
#5  do_malloc_or_cpp_alloc (size=<optimized out>) at src/tcmalloc.cc:1202
#6  do_realloc_with_callback (
    invalid_free_fn=0x7f6667913480 <(anonymous namespace)::InvalidFree(void*)>, invalid_get_size_fn=0x7f6667913500 <(anonymous namespace)::InvalidGetSizeForRealloc(void const*)>, new_size=689, old_ptr=0x65450d0) at src/tcmalloc.cc:1380
#7  do_realloc (new_size=689, old_ptr=0x65450d0) at src/tcmalloc.cc:1403
#8  tc_realloc (old_ptr=0x65450d0, new_size=689) at src/tcmalloc.cc:1643
#9  0x00007f66579c7afe in sdsMakeRoomFor (s=0x65450d0 "", addlen=4294967296)
    at sds.c:142
#10 0x00007f66579c7c6a in sdscatlen (s=s@entry=0x65450d8 "",
    t=t@entry=0x841cf58, len=340) at sds.c:241
#11 0x00007f66579c5c70 in redisvFormatCommand (
    target=target@entry=0x7f66554784a8, format=<optimized out>,
    ap=0x7f66554784d8) at hiredis.c:267
#12 0x00007f66579d9056 in redisClustervAsyncCommand (acc=0x80b5780,
    fn=0x7f66638325d5 <getSetCallback(redisClusterAsyncContext*, void*, void*)>,---Type <return> to continue, or q <return> to quit---
privdata=0x6544ff0, format=<optimized out>, ap=<optimized out>)
    at hircluster.c:4720
#13 0x00007f66579d919d in redisClusterAsyncCommand (acc=<optimized out>,
    fn=<optimized out>, privdata=<optimized out>, format=<optimized out>)
    at hircluster.c:4742

**Comment by nginxsantos** [comment]
Any response on this?
